GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/64c1195bef0c56302ed9dd5a
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Man",
  "number": "123-456789"
}
### No body
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456789"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Man"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123-456789"
}
###
DELETE http://localhost:3001/api/persons/64c1274840bdd42cd2dde280